swagger: '2.0'
info:
  description: TMG Recommender API definition
  version: '0.1'
  title: TMG Recommender
  termsOfService: ''
  contact:
    email: richard.spence@telegraph.co.uk
basePath: /v1
schemes:
  - http
  - https
paths:
  /recommend-articles/by-article:
    post:
      summary: Get Article recommendations based on an Article
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            This is the request object that passes the Article we want
            recommendations based on and some query parameters and filters
          required: true
          schema:
            $ref: '#/definitions/def-request-json'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/def-response-json'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
definitions:
  error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 400
      status:
        type: string
        example: Bad Request
  service-error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 500
      status:
        type: string
        example: 'Service error:....'
    required:
      - status
  def-request-json:
    type: object
    properties:
      sort:
        type: string
        example: '-score'
      limit:
        type: integer
        format: int64
        example: 40
      offset:
        type: integer
        format: int64
        example: 20
      query-filters:
        $ref: '#/definitions/def-query-filters'
      query-object:
        $ref: '#/definitions/def-query-object-article'
  def-query-filters:
    type: object
    properties:
      type:
        type: array
        items:
          type: string
        example:
          - article
          - image
      source:
        type: array
        items:
          type: string
        example:
          - Reuters
          - PA
      date-from:
        type: string
        format: date-time
        example: '2017-10-17T10:00:00Z'
      date-to:
        type: string
        format: date-time
        example: '2017-10-18T10:00:00Z'
      channel:
        type: array
        items:
          type: string
        example:
          - news
          - football
  def-query-object-article:
    type: object
    properties:
      headline:
        type: string
        example: Lorem ipsum dolor sit amet
      channel:
        type: string
        example: news
      body:
        type: string
        example: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac
          sollicitudin erat, sit amet efficitur ligula. Pellentesque eget
          convallis elit. Nam enim neque, suscipit placerat tempus quis, iaculis
          id neque. Ut id ante quis magna euismod accumsan.
  def-response-json:
    type: object
    properties:
      code:
        type: integer
        format: int64
        example: 200
      status:
        type: string
        example: Success
      result-count:
        type: integer
        format: int64
        example: 4
      data:
        $ref: '#/definitions/def-article-recommendation-array'
  def-article-recommendation-array:
    type: array
    items:
      $ref: '#/definitions/def-article-recommendation'
  def-article-recommendation:
    type: object
    properties:
      id:
        type: string
        example: f7296379-b0c5-11e7-a470-06401c187d50
      score:
        type: number
        format: float
        example: 0.5
      type:
        type: string
        example: article
      headline:
        type: string
        example: Game of Thrones cast 'won't be given scripts' for season 8
      url:
        type: string
        format: url
        example: >-
          http://www.telegraph.co.uk/tv/2017/10/14/game-thrones-cast-wont-given-scripts-season-8/
      thumbnail:
        type: string
        format: url
        example: >-
          http://www.telegraph.co.uk/content/dam/tv/2017/08/28/TELEMMGLPICT000136302403-thumbnail_trans_NvBQzQNjv4BqaRL1kC4G7DT9ZsZm6Pe3PehAFAI_f6ud569StXyOKH0.jpeg
      pubdate:
        type: string
        format: date-time
        example: '2017-10-14T11:38:36Z'
      channel:
        type: string
        example: tv
      source:
        type: string
        example: tmg
      authors:
        type: array
        items:
          type: string
        example:
          - Sophie Christie
          - Richard Dyson
